"""initial database schema

Revision ID: 1711233915dd
Revises:
Create Date: 2026-08-23 22:38:19.494358

"""
from alembic import op
import sqlalchemy as sa
from app.core.db_types import GUID
revision = '1711233915dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'SYSTEM_MANAGER', 'EXAM_MANAGER', 'SCORE_OPERATOR', 'USER_OPERATOR', 'SUPPORT', 'OBSERVER', name='adminrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('appearance_settings',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('system_title', sa.String(length=150), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('background_color', sa.String(length=7), nullable=False),
    sa.Column('font_family', sa.String(length=150), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('result_message_template', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_admin_id', GUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('broadcast_jobs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('exam_id', GUID(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'SENT', 'CANCELLED', 'FAILED', name='broadcastjobstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('created_by_admin_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('exam_code', sa.String(length=50), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('passing_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ENTERING_SCORES', 'READY_FOR_REVIEW', 'PUBLISHED', 'CLOSED', name='examstatus'), nullable=False),
    sa.Column('results_publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_exam_code'), 'exams', ['exam_code'], unique=True)
    op.create_table('feature_flags',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('bale_user_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('national_code', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='userstatus'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_bale_user_id'), 'users', ['bale_user_id'], unique=True)
    op.create_index(op.f('ix_users_national_code'), 'users', ['national_code'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('correction_requests',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('previous_value', sa.String(length=255), nullable=True),
    sa.Column('requested_value', sa.String(length=255), nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_admin_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_requests_user_id'), 'correction_requests', ['user_id'], unique=False)
    op.create_table('report_cards',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('report_number', sa.String(length=30), nullable=False),
    sa.Column('verification_code', sa.String(length=64), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('qr_path', sa.String(length=500), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_cards_report_number'), 'report_cards', ['report_number'], unique=True)
    op.create_index(op.f('ix_report_cards_user_id'), 'report_cards', ['user_id'], unique=True)
    op.create_index(op.f('ix_report_cards_verification_code'), 'report_cards', ['verification_code'], unique=True)
    op.create_table('results',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('exam_id', GUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('RECORDED', 'REVIEWED', 'PUBLISHED', 'VOIDED', name='resultstatus'), nullable=False),
    sa.Column('recorded_by_admin_id', GUID(), nullable=True),
    sa.Column('published_by_admin_id', GUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['published_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_exam_id'), 'results', ['exam_id'], unique=False)
    op.create_index(op.f('ix_results_user_id'), 'results', ['user_id'], unique=False)
    op.create_table('objections',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('result_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='objectionstatus'), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_admin_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objections_result_id'), 'objections', ['result_id'], unique=False)
    op.create_index(op.f('ix_objections_user_id'), 'objections', ['user_id'], unique=False)
    op.create_table('result_history',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('result_id', GUID(), nullable=False),
    sa.Column('previous_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('new_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('changed_by_admin_id', GUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_history_result_id'), 'result_history', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_history_result_id'), table_name='result_history')
    op.drop_table('result_history')
    op.drop_index(op.f('ix_objections_user_id'), table_name='objections')
    op.drop_index(op.f('ix_objections_result_id'), table_name='objections')
    op.drop_table('objections')
    op.drop_index(op.f('ix_results_user_id'), table_name='results')
    op.drop_index(op.f('ix_results_exam_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_report_cards_verification_code'), table_name='report_cards')
    op.drop_index(op.f('ix_report_cards_user_id'), table_name='report_cards')
    op.drop_index(op.f('ix_report_cards_report_number'), table_name='report_cards')
    op.drop_table('report_cards')
    op.drop_index(op.f('ix_correction_requests_user_id'), table_name='correction_requests')
    op.drop_table('correction_requests')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_national_code'), table_name='users')
    op.drop_index(op.f('ix_users_bale_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_exams_exam_code'), table_name='exams')
    op.drop_table('exams')
    op.drop_table('broadcast_jobs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('appearance_settings')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
